export const MainflowNode1: any = [
  {
    id: 'test-method-0',
    type: 'test-method',
    position: { x: 256, y: 101 },
    data: { label: 'Leakage', id: 'Leakage' },
    TestNumber: null,
    LoopCount: 1,
    Class: 'Leakage',
    width: 150,
    height: 110,
  },
  {
    id: 'test-method-1',
    type: 'test-method',
    position: { x: 255, y: 268 },
    data: { label: 'LoadAllCfgRegFromFile', id: 'LoadAllCfgRegFromFile' },
    TestNumber: null,
    LoopCount: 2,
    Class: 'LoadAllCfgRegFromFile',
    width: 150,
    height: 129,
    selected: false,
    positionAbsolute: { x: 255, y: 268 },
    dragging: false,
  },
  {
    id: 'subflow-2',
    type: 'subflow',
    position: { x: 253, y: 442 },
    data: { label: 'subflow 2', id: '' },
    TestNumber: '111',
    LoopCount: 2,
    Class: '',
    width: 150,
    height: 110,
    selected: false,
    positionAbsolute: { x: 253, y: 442 },
    dragging: false,
  },
  {
    id: 'test-method-CustomTestItem',
    type: 'test-method',
    position: { x: 252, y: 599 },
    data: { label: 'CustomTestItem' },
    Class: 'CustomTestItem',
    LoopCount: 1,
    width: 150,
    height: 110,
    selected: false,
    positionAbsolute: { x: 252, y: 599 },
    dragging: false,
  },
  {
    id: 'fen-bin-FB1',
    type: 'fen-bin',
    position: { x: 571, y: 149 },
    data: { label: 'FB1', id: '' },
    TestNumber: null,
    LoopCount: 1,
    Class: '',
    width: 82,
    height: 82,
  },
  {
    id: 'fen-bin-FB2',
    type: 'fen-bin',
    position: { x: 603, y: 313 },
    data: { label: 'FB2', id: '' },
    TestNumber: null,
    LoopCount: 1,
    Class: '',
    width: 82,
    height: 82,
  },
  {
    id: 'fen-bin-PB3',
    type: 'fen-bin',
    position: { x: 606.1770031549454, y: 453.48979106170964 },
    data: { label: 'PB3', id: '' },
    TestNumber: null,
    LoopCount: 1,
    Class: '',
    width: 82,
    height: 82,
    selected: false,
    positionAbsolute: { x: 606.1770031549454, y: 453.48979106170964 },
    dragging: false,
  },
  {
    id: 'fen-bin-PB4',
    type: 'fen-bin',
    position: { x: 601.6170031549455, y: 626.7697910617097 },
    data: { label: 'PB4', id: '' },
    TestNumber: null,
    LoopCount: 1,
    Class: '',
    width: 82,
    height: 82,
    selected: true,
    positionAbsolute: { x: 601.6170031549455, y: 626.7697910617097 },
    dragging: false,
  },
  {
    id: 'subflow-3',
    type: 'subflow',
    position: { x: 247.45700315494543, y: 762.0497910617095 },
    data: { label: 'subflow 1', id: '' },
    TestNumber: '000',
    LoopCount: 1,
    Class: '',
    width: 150,
    height: 110,
    selected: false,
    positionAbsolute: { x: 247.45700315494543, y: 762.0497910617095 },
    dragging: false,
  },
];

export const MainflowEdge1: any = [
  {
    id: '1->3',
    source: '1',
    target: '3',
  },
  {
    id: '2->4',
    source: '2',
    target: '4',
  },
  {
    id: '2->5',
    source: '2',
    target: '5',
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '1',
    source: 'test-method-0',
    sourceHandle: null,
    target: 'fen-bin-FB1',
    targetHandle: null,
    id: 'reactflow__edge-test-method-0-fen-bin-FB1',
    selected: false,
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '0',
    source: 'test-method-0',
    sourceHandle: null,
    target: 'test-method-1',
    targetHandle: null,
    id: 'reactflow__edge-test-method-0-test-method-1',
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '0',
    source: 'test-method-1',
    sourceHandle: null,
    target: 'subflow-2',
    targetHandle: null,
    id: 'reactflow__edge-test-method-1-subflow-2',
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '0',
    source: 'subflow-2',
    sourceHandle: null,
    target: 'test-method-CustomTestItem',
    targetHandle: null,
    id: 'reactflow__edge-subflow-2-test-method-CustomTestItem',
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '0',
    source: 'test-method-CustomTestItem',
    sourceHandle: null,
    target: 'subflow-3',
    targetHandle: null,
    id: 'reactflow__edge-test-method-CustomTestItem-subflow-3',
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '1',
    source: 'test-method-1',
    sourceHandle: null,
    target: 'fen-bin-FB2',
    targetHandle: null,
    id: 'reactflow__edge-test-method-1-fen-bin-FB2',
    selected: false,
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '1',
    source: 'subflow-2',
    sourceHandle: null,
    target: 'fen-bin-PB3',
    targetHandle: null,
    id: 'reactflow__edge-subflow-2-fen-bin-PB3',
    selected: false,
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '1',
    source: 'test-method-CustomTestItem',
    sourceHandle: null,
    target: 'fen-bin-PB4',
    targetHandle: null,
    id: 'reactflow__edge-test-method-CustomTestItem-fen-bin-PB4',
    selected: false,
  },
];
