export const SubflowNode2: any = [
  {
    id: '1',
    data: { label: 'start' },
    position: { x: 102, y: 100 },
    type: 'test-method',
    width: 100,
    height: 70,
    selected: false,
    dragging: false,
    positionAbsolute: { x: 102, y: 100 },
  },
  {
    id: '2',
    data: { label: 'Node 2' },
    position: { x: 100, y: 250 },
    type: 'test-method',
    width: 150,
    height: 110,
  },
  {
    id: 'test-method-ReadPagesShmooDDWMode12_Name',
    type: 'test-method',
    position: { x: 98, y: 411 },
    data: { label: 'ReadPagesShmooDDWMode12_Name' },
    Class: 'ReadPagesShmooDDWMode12_Class',
    LoopCount: 1,
    width: 150,
    height: 129,
    selected: false,
    positionAbsolute: { x: 98, y: 411 },
    dragging: false,
  },
  {
    id: 'fen-bin-FB2',
    type: 'fen-bin',
    position: { x: 407, y: 263 },
    data: { label: 'FB2' },
    TestNumber: null,
    LoopCount: 1,
    Class: '',
    width: 82,
    height: 82,
    selected: false,
    positionAbsolute: { x: 407, y: 263 },
    dragging: false,
  },
  {
    id: 'fen-bin-FB1',
    type: 'fen-bin',
    position: { x: 407, y: 131 },
    data: { label: 'FB1' },
    TestNumber: null,
    LoopCount: 1,
    Class: '',
    width: 82,
    height: 82,
    selected: false,
    positionAbsolute: { x: 407, y: 131 },
    dragging: false,
  },
  {
    id: 'fen-bin-PB3',
    type: 'fen-bin',
    position: { x: 419, y: 461 },
    data: { label: 'PB3' },
    TestNumber: null,
    LoopCount: 1,
    Class: '',
    width: 82,
    height: 82,
  },
  {
    id: 'fen-bin-PB4',
    type: 'fen-bin',
    position: { x: 156, y: 577 },
    data: { label: 'PB4', id: '' },
    TestNumber: null,
    LoopCount: 1,
    Class: '',
    width: 82,
    height: 82,
    selected: false,
    positionAbsolute: { x: 156, y: 577 },
    dragging: false,
  },
];

export const SubflowEdge2: any = [
  {
    id: 'e1-2',
    source: '1',
    target: '2',
    type: 'floating',
  },
  {
    id: '2->5',
    source: '2',
    target: '5',
  },
  {
    id: '5->5',
    source: '5',
    target: '5',
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '0',
    source: '2',
    sourceHandle: null,
    target: 'test-method-ReadPagesShmooDDWMode12_Name',
    targetHandle: null,
    id: 'reactflow__edge-2-test-method-ReadPagesShmooDDWMode12_Name',
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '0',
    source: 'test-method-ReadPagesShmooDDWMode12_Name',
    sourceHandle: null,
    target: 'fen-bin-PB4',
    targetHandle: null,
    id: 'reactflow__edge-test-method-ReadPagesShmooDDWMode12_Name-fen-bin-PB4',
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '1',
    source: 'test-method-ReadPagesShmooDDWMode12_Name',
    sourceHandle: null,
    target: 'fen-bin-PB3',
    targetHandle: null,
    id: 'reactflow__edge-test-method-ReadPagesShmooDDWMode12_Name-fen-bin-PB3',
    selected: false,
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '1',
    source: '2',
    sourceHandle: null,
    target: 'fen-bin-FB2',
    targetHandle: null,
    id: 'reactflow__edge-2-fen-bin-FB2',
    selected: false,
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '1',
    source: '1',
    sourceHandle: null,
    target: 'fen-bin-FB1',
    targetHandle: null,
    id: 'reactflow__edge-1-fen-bin-FB1',
    selected: false,
  },
];
