import { Position } from 'reactflow';

export const subflowNode: any = [
  {
    id: 'subflow',
    data: { label: 'subflow-test' },
    type: 'custom-subflow',
    position: { x: 0, y: 0 },
    style: {
      background: 'rgba(187, 255, 170, 0.2)',
      width: 700,
      height: 700,
    },
  },
  {
    id: 'subflow-1',
    type: 'custom-input',
    data: { label: 'Node-01' },
    position: { x: 350, y: 10 },
    parentNode: 'subflow',
    extent: 'parent',
  },
  {
    id: 'subflow2',
    type: 'output',
    data: { label: 'Group A' },
    position: { x: 100, y: 100 },
    style: { backgroundColor: 'rgba(255, 0, 0, 0.2)', width: 200, height: 200 },
    parentNode: 'subflow',
    extent: 'parent',
  },
  {
    id: 'subflow2a',
    targetPosition: Position.Top,
    data: { label: 'Node A.1' },
    position: { x: 5, y: 50 },
    parentNode: 'subflow2',
    extent: 'parent',
  },
  {
    id: 'subflow3',
    data: { label: 'subflowNode 1' },
    position: { x: 320, y: 100 },
    parentNode: 'subflow',
    extent: 'parent',
  },
  {
    id: 'subflow4',
    type: 'output',
    data: { label: 'Group B' },
    position: { x: 320, y: 200 },
    style: { backgroundColor: 'rgba(255, 0, 0, 0.2)', width: 300, height: 300 },
    parentNode: 'subflow',
    extent: 'parent',
  },
  {
    id: 'subflow4a',
    type: 'input',
    data: { label: 'Node B.1' },
    position: { x: 15, y: 65 },
    parentNode: 'subflow4',
    extent: 'parent',
  },
  {
    id: 'subflow4b',
    type: 'output',
    data: { label: 'Group B.A' },
    position: { x: 15, y: 120 },
    style: {
      backgroundColor: 'rgba(255, 0, 255, 0.2)',
      height: 150,
      width: 270,
    },
    parentNode: 'subflow4',
    extent: 'parent',
  },
  {
    id: 'subflow4b1',
    type: 'input',
    data: { label: 'Node B.A.1' },
    position: { x: 20, y: 40 },
    parentNode: 'subflow4b',
    extent: 'parent',
  },
  {
    id: 'subflow4b2',
    type: 'output',
    data: { label: 'Node B.A.2' },
    position: { x: 100, y: 100 },
    parentNode: 'subflow4b',
    extent: 'parent',
  },
];
