export const subflowNode: any = [
  {
    id: 'subflow1',
    type: 'input',
    data: { label: 'Node 0' },
    position: { x: 250, y: 5 },
    className: 'light',
  },
  {
    id: 'subflow2',
    data: { label: 'Group A' },
    position: { x: 100, y: 100 },
    className: 'light',
    style: { backgroundColor: 'rgba(255, 0, 0, 0.2)', width: 200, height: 200 },
  },
  {
    id: 'subflow2a',
    data: { label: 'Node A.1' },
    position: { x: 10, y: 50 },
    parentNode: 'subflow2',
  },
  {
    id: 'subflow3',
    data: { label: 'subflowNode 1' },
    position: { x: 320, y: 100 },
    className: 'light',
  },
  {
    id: 'subflow4',
    data: { label: 'Group B' },
    position: { x: 320, y: 200 },
    className: 'light',
    style: { backgroundColor: 'rgba(255, 0, 0, 0.2)', width: 300, height: 300 },
  },
  {
    id: '4a',
    data: { label: 'Node B.1' },
    position: { x: 15, y: 65 },
    className: 'light',
    parentNode: 'subflow4',
    extent: 'parent',
  },
  {
    id: 'subflow4b',
    data: { label: 'Group B.A' },
    position: { x: 15, y: 120 },
    className: 'light',
    style: {
      backgroundColor: 'rgba(255, 0, 255, 0.2)',
      height: 150,
      width: 270,
    },
    parentNode: 'subflow4',
  },
  {
    id: 'subflow4b1',
    data: { label: 'Node B.A.1' },
    position: { x: 20, y: 40 },
    className: 'light',
    parentNode: 'subflow4b',
  },
  {
    id: 'subflow4b2',
    data: { label: 'Node B.A.2' },
    position: { x: 100, y: 100 },
    className: 'light',
    parentNode: 'subflow4b',
  },
];
