export const SubflowNode2: any = [
  {
    id: 'test-method-0',
    type: 'test-method',
    position: {
      x: 355,
      y: 63,
    },
    data: {
      label: 'Leakage',
      id: 'Leakage',
    },
    TestNumber: null,
    LoopCount: 1,
    Class: 'Leakage',
    width: 150,
    height: 110,
    selected: false,
    positionAbsolute: {
      x: 355,
      y: 63,
    },
    dragging: false,
  },
  {
    id: 'subflow-2',
    type: 'subflow',
    position: {
      x: 354.19793419988156,
      y: 219.10031082465906,
    },
    data: {
      label: 'subflow 1',
      id: '',
    },
    TestNumber: '000',
    LoopCount: 3,
    Class: '',
    width: 150,
    height: 110,
    selected: false,
    positionAbsolute: {
      x: 354.19793419988156,
      y: 219.10031082465906,
    },
    dragging: false,
  },
  {
    id: 'test-method-3',
    type: 'test-method',
    position: {
      x: 350.8753896800887,
      y: 372.387141412149,
    },
    data: {
      label: 'LoadAllCfgRegFromFile',
      id: 'LoadAllCfgRegFromFile',
    },
    TestNumber: null,
    LoopCount: 2,
    Class: 'LoadAllCfgRegFromFile',
    width: 150,
    height: 129,
    selected: false,
    positionAbsolute: {
      x: 350.8753896800887,
      y: 372.387141412149,
    },
    dragging: false,
  },
  {
    id: 'fen-bin-FB1-4',
    type: 'fen-bin',
    position: {
      x: 678.0424475721106,
      y: 95.25447740706113,
    },
    data: {
      label: 'FB1',
      id: '',
    },
    TestNumber: null,
    LoopCount: 2,
    Class: '',
    width: 82,
    height: 82,
    selected: false,
    positionAbsolute: {
      x: 678.0424475721106,
      y: 95.25447740706113,
    },
    dragging: false,
  },
  {
    id: 'fen-bin-FB1-5',
    type: 'fen-bin',
    position: {
      x: 670.4638647395586,
      y: 233.1846849595074,
    },
    data: {
      label: 'FB1',
      id: '',
    },
    TestNumber: null,
    LoopCount: 2,
    Class: '',
    width: 82,
    height: 82,
    selected: false,
    positionAbsolute: {
      x: 670.4638647395586,
      y: 233.1846849595074,
    },
    dragging: false,
  },
  {
    id: 'fen-bin-PB3-6',
    type: 'fen-bin',
    position: {
      x: 382.47771710258286,
      y: 559.063746759243,
    },
    data: {
      label: 'PB3',
      id: '',
    },
    TestNumber: null,
    LoopCount: 2,
    Class: '',
    width: 82,
    height: 82,
    selected: false,
    positionAbsolute: {
      x: 382.47771710258286,
      y: 559.063746759243,
    },
    dragging: false,
  },
  {
    id: 'fen-bin-FB2-8',
    type: 'fen-bin',
    position: {
      x: 678.0424475721106,
      y: 395.36635757612,
    },
    data: {
      label: 'FB2',
      id: '',
    },
    TestNumber: null,
    LoopCount: 2,
    Class: '',
    width: 82,
    height: 82,
    selected: false,
    positionAbsolute: {
      x: 678.0424475721106,
      y: 395.36635757612,
    },
    dragging: false,
  },
];
export const SubflowEdge2: any = [
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '1',
    source: 'test-method-0',
    sourceHandle: null,
    target: 'fen-bin-FB1-4',
    targetHandle: null,
    id: 'reactflow__edge-test-method-0-fen-bin-FB1-4',
    selected: false,
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '1',
    source: 'subflow-2',
    sourceHandle: null,
    target: 'fen-bin-FB1-5',
    targetHandle: null,
    id: 'reactflow__edge-subflow-2-fen-bin-FB1-5',
    selected: false,
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '1',
    source: 'test-method-3',
    sourceHandle: null,
    target: 'fen-bin-FB2-8',
    targetHandle: null,
    id: 'reactflow__edge-test-method-3-fen-bin-FB2-8',
    selected: true,
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '0',
    source: 'test-method-3',
    sourceHandle: null,
    target: 'fen-bin-PB3-6',
    targetHandle: null,
    id: 'reactflow__edge-test-method-3-fen-bin-PB3-6',
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '0',
    source: 'test-method-0',
    sourceHandle: null,
    target: 'subflow-2',
    targetHandle: null,
    id: 'reactflow__edge-test-method-0-subflow-2',
  },
  {
    style: {
      strokeWidth: 1,
      stroke: 'black',
    },
    type: 'floating',
    markerEnd: {
      type: 'arrowclosed',
      color: 'black',
    },
    label: '0',
    source: 'subflow-2',
    sourceHandle: null,
    target: 'test-method-3',
    targetHandle: null,
    id: 'reactflow__edge-subflow-2-test-method-3',
  },
];
